services:
  python-app:
    build:
      context: ./python-server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: python -m uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PYTHONUNBUFFERED=1

  node-app:
    build:
      context: ./node-server/node-server
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    command: npm start
    environment:
      - PORT=8001
    depends_on:
      - python-app
