@Tejasri-T ➜ /workspaces/Anythink-Market-og6zjceg (newbranch) $ git push -u origin main
branch 'main' set up to track 'origin/main'.
Everything up-to-date
@Tejasri-T ➜ /workspaces/Anythink-Market-og6zjceg (newbranch) $ git push -u newbranch
fatal: 'newbranch' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
@Tejasri-T ➜ /workspaces/Anythink-Market-og6zjceg (newbranch) $ git push newbranch
fatal: 'newbranch' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
@Tejasri-T ➜ /workspaces/Anythink-Market-og6zjceg (newbranch) $ 